E-Commerce.Web/Controllers/DireccionEnvioController.cs
using E_Commerce.Data.DTOs.EntititesDto;
using E_Commerce.Data.Entities;
using E_Commerce.Data.Interfaces.Services;
using E_Commerce.Data.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace E_Commerce.Web.Controllers
{
    public class DireccionEnvioController : Controller
    {
        private readonly IDireccionEnvioServices _services;
        public DireccionEnvioController( IDireccionEnvioServices services)
        {
            _services = services;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {

            var listaDireccionesDto = await _services.GetAllListDto();

            var listaDireccionesViewModel = listaDireccionesDto.Select(d => new DireccionEnvioViewModel
            {
                Id = d.Id,
                Calle = d.Calle,
                Ciudad = d.Ciudad,
                CodigoPostal = d.CodigoPostal,
                Pais = d.Pais,
                PedidoId = d.PedidoId
            }).ToList();

            return View(listaDireccionesViewModel);
        }

        [HttpGet]
        public IActionResult Crear()
        {
            return View("Crear", new DireccionEnvioViewModel() { Calle = "", Ciudad = "", CodigoPostal = "", Pais = "" });
        }

        [HttpPost]
        public async Task<IActionResult> Crear(DireccionEnvioViewModel save)
        {
            if (!ModelState.IsValid)
            {
                return View("Crear", save);
            }
            var direccionDto = new DireccionEnvioDto
            {
                Calle = save.Calle,
                Ciudad = save.Ciudad,
                CodigoPostal = save.CodigoPostal,
                Pais = save.Pais,
                PedidoId = save.PedidoId ?? 0
            };
            await _services.SaveDtoAsync(direccionDto);
            return RedirectToAction("Index");
        }
    }
}

E-Commerce.Web/Views/DireccionEnvio/Crear.cshtml
@model DireccionEnvioViewModel
@{
    ViewData["Title"] = "Crear Dirección";
}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow rounded">
                <div class="card-header bg-primary text-white">
                    <h4 class="mb-0"><i class="fa fa-flag me-2"></i>Agregar Direccion de Envio</h4>
                </div>
                <div class="card-body">
                    <form asp-action="Crear" asp-controller="DireccionEnvio" method="post">
                        <div asp-validation-summary="ModelOnly"></div>

                        <div class="mb-3">
                            <label asp-for="Calle" class="form-label">Calle</label>
                            <input asp-for="Calle" class="form-control" placeholder="Ingresa la calle" />
                            <span asp-validation-for="Calle" class="text-danger small"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="Ciudad" class="form-label">Ciudad</label>
                            <input asp-for="Ciudad" class="form-control" placeholder="Santo Domingo" />
                            <span asp-validation-for="Ciudad" class="text-danger small"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="Pais" class="form-label">Pais</label>
                            <input asp-for="Pais" class="form-control" placeholder="Ingresa la calle" />
                            <span asp-validation-for="Pais" class="text-danger small"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="CodigoPostal" class="form-label">Codigo Postal</label>
                            <input asp-for="CodigoPostal" class="form-control" placeholder="30100" />
                            <span asp-validation-for="CodigoPostal" class="text-danger small"></span>
                        </div>

                        <div class="d-flex justify-content-between mt-3">
                            <a asp-controller="DireccionEnvio" asp-action="Index" class="btn btn-secondary">
                                <i class="fa fa-arrow-left me-1"></i>Volver Atrás
                            </a>

                            <button type="submit" class="btn btn-success">
                                <i class="fa fa-plus me-1"></i>Agregar Dirección
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

E-Commerce.Web/Views/DireccionEnvio/Index.cshtml
@model List<DireccionEnvioViewModel>
@{
    ViewData["Title"] = "Tus Direcciones index";
}

<div class="container mt-4">
    <div class="row mb-2">
        <div class="col text-end">
            <a asp-action="Crear" asp-controller="DireccionEnvio" class="btn btn-success btn-lg">
                <i class="fa fa-plus me-2"></i>Agregar nueva Direccion
            </a>
        </div>
    </div>
    <div class="card shadow rounded">
        <div class="card-header bg-primary text-white">
            <h4 class="mb-0">Lista de Direcciones</h4>
        </div>
        <div class="table">
            @if (Model.Any())
            {
                <div class="table-responsive">
                    <table class="table table-striped table-hover table-bordered align-middle text-center" id="tblCountry">
                        <thead class="table-dark">
                            <tr>
                                <th>#</th>
                                <th>Pais</th>
                                <th>Ciudad</th>
                                <th>Calle</th>
                                <th>CodigoPostal</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(m => item.Id)</td>
                                    <td>@Html.DisplayFor(m => item.Pais)</td>
                                    <td>@Html.DisplayFor(m => item.Ciudad)</td>
                                    <td>@Html.DisplayFor(m => item.Calle)</td>
                                    <td>@Html.DisplayFor(m => item.CodigoPostal)</td>
                                    <td>
                                        <a class="btn btn-sm btn-warning me-1" asp-action="Editar" asp-route-id="@item.Id">
                                            <i class="fa fa-pencil"></i> Editar
                                        </a>
                                        <a class="btn btn-sm btn-info text-white me-1" asp-action="Detalles" asp-route-id="@item.Id">
                                            <i class="fa fa-info-circle"></i> Detalles
                                        </a>
                                        <a class="btn btn-sm btn-danger" asp-action="Borrar" asp-route-id="@item.Id">
                                            <i class="fa fa-trash"></i> Borrar
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            }
            else
            {
                <div class="alert alert-warning text-center" role="alert">
                    No hay registros disponibles.
                </div>
            }
        </div>
    </div>
</div>