E-Commerce.Web/Controllers/ProductoController.cs
using E_Commerce.Data.DTOs.EntititesDto;
using E_Commerce.Data.Interfaces.Services;
using E_Commerce.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace E_Commerce.Web.Controllers
{
    public class ProductoController : Controller
    {
        private readonly IProductoServices _services;
        private readonly ICategoriaServices _categories;

        public ProductoController(IProductoServices productoServices, ICategoriaServices categories)
        {
            _services = productoServices;
            _categories = categories;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var dto = await _services.GetAllListDto();

            var listEntity = dto.Select(s =>
            new ProductoViewModel()
            {
                Id = s.Id,
                Nombre = s.Nombre,
                Descripcion = s.Descripcion,
                Stock = s.Stock,
                EsNuevo = s.EsNuevo,
                EsPopular = s.EsPopular,
                Marca = s.Marca,
                Precio = s.Precio,
                CategoriaId = s.CategoriaId,
                Categoria = s.Categoria == null ? null : new CategoriaViewModel()
                {
                    Id = s.Id,
                    Nombre = s.Nombre,
                    Descripcion = s.Descripcion,
                }

            }).ToList();

            return View(listEntity);
        }

        [HttpGet]
        public async Task<IActionResult> Crear()
        {
            ViewBag.Categoria = await _categories.GetAllListDto();

            return View("Crear", new SaveProductosViewModel() { Nombre = "", Descripcion = "", Stock = 0, EsNuevo = true, EsPopular = false, Marca = "", Precio = 0, CategoriaId = 0 });
        }

        [HttpPost]
        public async Task<IActionResult> Crear(SaveProductosViewModel save)
        {
            ViewBag.Categoria = await _categories.GetAllListDto();

            if (ModelState.IsValid)
            {
                ProductoDto dto = new() 
                { Id = 0, Nombre = save.Nombre,
                  Descripcion = save.Descripcion,
                  Stock = save.Stock,
                  EsNuevo = save.EsNuevo,
                  EsPopular = save.EsPopular,
                  Marca = save.Marca,
                  Precio = save.Precio,
                  CategoriaId = save.CategoriaId 
                };
                await _services.SaveDtoAsync(dto);
                return RedirectToAction(nameof(Index));
            }
            return View("Crear", save);
        }
    }
}

E-Commerce.Web/Controllers/PromocionController.cs
using E_Commerce.Data.DTOs.EntititesDto;
using E_Commerce.Data.Interfaces.Services;
using E_Commerce.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace E_Commerce.Web.Controllers
{
    public class PromocionController : Controller
    {
        private readonly IPromocionServices _services;
        public PromocionController(IPromocionServices service)
        {
            _services = service;
        }
        
        public async Task<IActionResult> Index()
        {
            var dto = await _services.GetAllListDto();

            var listEntity = dto.Select(s =>
            new PromocionViewModel()
            {
                Id = s.Id,
                Titulo = s.Titulo,
                Descripcion = s.Descripcion,
                ImagenUrl = s.ImagenUrl
            }).ToList();

            return View(listEntity);
        }

        [HttpGet]
        public async Task<IActionResult> Crear()
        {
            return View("Crear", new SavePromocionViewModel()
            {
                Id = 0,
                Titulo = "",
                Descripcion = "",
                ImagenUrl = ""
            });
        }

        [HttpPost]
        public async Task<IActionResult> Crear(SavePromocionViewModel vm)
        {
            if (ModelState.IsValid)
            {
                PromocionDto dto = new()
                {
                    Id = vm.Id,
                    Titulo = vm.Titulo,
                    Descripcion = vm.Descripcion,
                    ImagenUrl = vm.ImagenUrl
                };
                await _services.SaveDtoAsync(dto);
                return RedirectToAction(nameof(Index));
            }
            return View("Crear", vm);
        }


    }
}

E-Commerce.Web/Views/Promocion/Crear.cshtml
@model SavePromocionViewModel
@{
    ViewData["Title"] = "Crear Promocion";
}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow rounded">
                <div class="card-header bg-primary text-white">
                    <h4 class="mb-0"><i class="fa fa-flag me-2"></i>Agregar Promocion</h4>
                </div>
                <div class="card-body">
                    <form asp-action="Crear" method="post">
                        <div asp-validation-summary="ModelOnly"></div>

                        <div class="mb-3">
                            <label asp-for="Titulo" class="form-label">Titulo</label>
                            <input asp-for="Titulo" class="form-control" placeholder="Ingresa el Titulo" />
                            <span asp-validation-for="Titulo" class="text-danger small"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="Descripcion" class="form-label">Descripcion</label>
                            <input asp-for="Descripcion" class="form-control" placeholder="" />
                            <span asp-validation-for="Descripcion" class="text-danger small"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="ImagenUrl" class="form-label">ImagenUrl</label>
                            <input asp-for="ImagenUrl" class="form-control" placeholder="" />
                            <span asp-validation-for="ImagenUrl" class="text-danger small"></span>
                        </div>

                        <div class="d-flex justify-content-between mt-3">
                            <a asp-controller="Producto" asp-action="Index" class="btn btn-secondary">
                                <i class="fa fa-arrow-left me-1"></i>Volver Atras
                            </a>

                            <button type="submit" class="btn btn-success">
                                <i class="fa fa-plus me-1"></i>Agregar Promocion
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

E-Commerce.Web/Views/Promocion/Index.cshtml
@model IEnumerable<PromocionViewModel>
@{
    ViewData["Title"] = "Promocion index";
}


<div class="row">
    <div class="text-center">
        <h2 class="display-4">Promocion</h2>
    </div>
</div>

<div class="row mb-2">
    <div class="col text-end">
        <a asp-action="Crear" asp-controller="Promocion" class="btn btn-success btn-lg">
            <i class="fa fa-plus me-2"></i>Agregar nueva promocion
        </a>
    </div>
</div>

<div class="row mt-2">
    @if (Model.Any())
    {
        foreach (var item in Model)
        {
            <div class="col-12 col-md-3">
                <div class="card">
                    <img src="@item.ImagenUrl" class="card-img-top responsive-image" alt="@item.Titulo">
                    <div class="card-body">
                        <h5 class="card-title">@item.Titulo</h5>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Description: @item.Descripcion</li>
                    </ul>
                    <div class="card-body">
                        <a class="btn btn-warning float-end" asp-controller="Promocion" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i> Edit</a>
                        <a class="btn btn-danger float-end me-2" asp-controller="Promocion" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i> Delete</a>
                    </div>
                </div>
            </div>
        }
    }
    else
    {
        <div class="text-center">
            <h5 class="display-4">No hay Promociones</h5>
        </div>
    }
</div>