E-Commerce.Web/Controllers/CategoriaController.cs
using E_Commerce.Data.DTOs.EntititesDto;
using E_Commerce.Data.Interfaces.Services;
using E_Commerce.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace E_Commerce.Web.Controllers
{
    public class CategoriaController : Controller
    {
        private readonly ICategoriaServices _categories;

        public CategoriaController(ICategoriaServices categories)
        {
            _categories = categories;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var dto = await _categories.GetAllListDto();

            var listEntity = dto.Select(s =>
            new CategoriaViewModel()
            {
                Id = s.Id,
                Nombre = s.Nombre,
                Descripcion = s.Descripcion
               
            }).ToList();

            return View(listEntity);
        }

        [HttpGet]
        public async Task<IActionResult> Crear()
        {
            ViewBag.Categoria = await _categories.GetAllListDto();

            return View("Crear", new CategoriaViewModel() { Nombre = "", Descripcion = "", });
        }


        [HttpPost]
        public async Task<IActionResult> Crear(SaveProductosViewModel save)
        {
            ViewBag.Categoria = await _categories.GetAllListDto();

            if (ModelState.IsValid)
            {
                CategoriaDto dto = new()
                {
                    Id = 0,
                    Nombre = save.Nombre,
                    Descripcion = save.Descripcion,
                  
                };
                await _categories.SaveDtoAsync(dto);
                return RedirectToAction(nameof(Index));
            }
            return View("Crear", save);
        }
    }
}

E-Commerce.Web/Controllers/CuponController.cs
using System.Runtime.Intrinsics.Arm;
using E_Commerce.Data.DTOs.EntititesDto;
using E_Commerce.Data.Interfaces.Services;
using E_Commerce.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace E_Commerce.Web.Controllers
{
    public class CuponController : Controller
    {
        private readonly ICuponServices _services;
        public CuponController(ICuponServices cuponServices)
        {
            _services = cuponServices;
      
        }
        public async Task<IActionResult> Index()
        {
            var dto = await _services.GetAllListDto();

            var listEntity = dto.Select(s =>
            new CuponViewModel()
            {
                Id = s.Id,
                Codigo = s.Codigo,
                Descuento = s.Descuento,
                FechaExpiracion = s.FechaExpiracion
            }).ToList();

            return View(listEntity);
        }


        [HttpGet]
        public async Task<IActionResult> Crear()
        {
            return View("Crear", new SaveCuponViewModel()
            {
                Id = 0,
                Codigo = "",
                Descuento = 0,
                FechaExpiracion = null
            });
        }

        [HttpPost]
        public async Task<IActionResult> Crear(SaveCuponViewModel vm)
        {
            if (ModelState.IsValid)
            {
                CuponDto dto = new()
                {
                    Id = 0,
                    Codigo = vm.Codigo,
                    Descuento = vm.Descuento,
                    FechaExpiracion = vm.FechaExpiracion
                };
                await _services.SaveDtoAsync(dto);
                return RedirectToAction(nameof(Index));
            }
            return View("Crear", vm);
        }

        
    }
}

E-Commerce.Web/Controllers/FavoritosController.cs
using E_Commerce.Data.Interfaces.Services;
using E_Commerce.Data.ViewModels;
using Humanizer;
using Microsoft.AspNetCore.Mvc;

namespace E_Commerce.Web.Controllers
{
    public class FavoritosController : Controller
    {
        private readonly IProductoServices _productoServices;

        public FavoritosController(IProductoServices productoServices)
        {
            _productoServices = productoServices;
        }

        public async Task<IActionResult> Index()
        {
            var favoriteProductsResult = await _productoServices.GetPopulaarProductsAsync(20); //first 20 products

            var list = favoriteProductsResult.Result?.Select(s =>
             new ProductoViewModel()
             {
                 Id = s.Id,
                 Nombre = s.Nombre,
                 Descripcion = s.Descripcion,
                 Stock = s.Stock,
                 EsNuevo = s.EsNuevo,
                 EsPopular = s.EsPopular,
                 Marca = s.Marca,
                 Precio = s.Precio,
                 CategoriaId = s.CategoriaId,
                 Categoria = s.Categoria == null ? null : new CategoriaViewModel()
                 {
                     Id = s.Id,
                     Nombre = s.Nombre,
                     Descripcion = s.Descripcion,
                 }

             }).ToList();

            return View(list);
        }
    }
}

E-Commerce.Web/Controllers/ProductoController.cs
using E_Commerce.Data.DTOs.EntititesDto;
using E_Commerce.Data.Interfaces.Services;
using E_Commerce.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace E_Commerce.Web.Controllers
{
    public class ProductoController : Controller
    {
        private readonly IProductoServices _services;
        private readonly ICategoriaServices _categories;

        public ProductoController(IProductoServices productoServices, ICategoriaServices categories)
        {
            _services = productoServices;
            _categories = categories;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var dto = await _services.GetAllListDto();

            var listEntity = dto.Select(s =>
            new ProductoViewModel()
            {
                Id = s.Id,
                Nombre = s.Nombre,
                Descripcion = s.Descripcion,
                Stock = s.Stock,
                EsNuevo = s.EsNuevo,
                EsPopular = s.EsPopular,
                Marca = s.Marca,
                Precio = s.Precio,
                CategoriaId = s.CategoriaId,
                Categoria = s.Categoria == null ? null : new CategoriaViewModel()
                {
                    Id = s.Id,
                    Nombre = s.Nombre,
                    Descripcion = s.Descripcion,
                }

            }).ToList();

            return View(listEntity);
        }

        [HttpGet]
        public async Task<IActionResult> Crear()
        {
            ViewBag.Categoria = await _categories.GetAllListDto();

            return View("Crear", new SaveProductosViewModel() { Nombre = "", Descripcion = "", Stock = 0, EsNuevo = true, EsPopular = false, Marca = "", Precio = 0, CategoriaId = 0 });
        }

        [HttpPost]
        public async Task<IActionResult> Crear(SaveProductosViewModel save)
        {
            ViewBag.Categoria = await _categories.GetAllListDto();

            if (ModelState.IsValid)
            {
                ProductoDto dto = new() 
                { Id = 0, Nombre = save.Nombre,
                  Descripcion = save.Descripcion,
                  Stock = save.Stock,
                  EsNuevo = save.EsNuevo,
                  EsPopular = save.EsPopular,
                  Marca = save.Marca,
                  Precio = save.Precio,
                  CategoriaId = save.CategoriaId 
                };
                await _services.SaveDtoAsync(dto);
                return RedirectToAction(nameof(Index));
            }
            return View("Crear", save);
        }
    }
}

E-Commerce.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - E_Commerce.Web</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/E_Commerce.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">E-Commerce</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Producto" asp-action="Index">Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categoria" asp-action="Index">Categoria</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cupon" asp-action="Index">Cupon</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DireccionEnvio" asp-action="Index"> Tus Direcciones</a>
                        </li>
                        <li class="nav-item">
                             <a class="nav-link text-dark" asp-area="" asp-controller="Promocion" asp-action="Index">Promocion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Favoritos" asp-action="Index">Favoritos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - E_Commerce.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>